[package]
name = "reconstr"
authors = ["Timofey Prodanov <timofey.prodanov@hhu.de>", "Tobias Marschall <tobias.marschall@hhu.de>"]
version = "0.0.1"
edition = "2021"

[dependencies]
htslib = { package = "rust-htslib", version = "0.40" }
num-format = "0.4"
num-traits = "0.2"
nalgebra = "0.31"
itertools = "0.10"
statrs = "0.16"
intmap = "2.0.0"
json = "0.12"
once_cell = "1.17"
# rand = "0.8.5"