[package]
name = "reconstr"
authors = ["Timofey Prodanov", "Tobias Marschall"]
version = "0.0.1"
edition = "2021"

[dependencies]
rust-htslib = "0.40"
num-format = "0.4"
num-traits = "0.2"
nalgebra = "0.31"
itertools = "0.10"
libm = "0.2"